name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - "**.h"
      - "**.hpp"
      - "**.dox"
      - "**.md"
      - "docs/**"
      - "**/docs.yml"
      - '.github/workflows/docs.yml'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install --no-install-recommends git python3 python3-pip doxygen
          sudo -H pip3 install --upgrade poxy

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare repository (on push)
        if: ${{ github.event_name == 'push' }}
        run: |
          git fetch origin ${{ github.ref_name }}:refs/remotes/origin/${{ github.ref_name }} --tags --force
          git remote set-head origin -a
          git checkout ${{ github.ref_name }}
          git pull --force

      - name: Prepare repository (on release)
        if: ${{ github.event_name == 'release' }}
        run: |
          git fetch origin master:refs/remotes/origin/master --tags --force
          git remote set-head origin -a
          git checkout ${{ github.ref_name }}
          git pull --force

      - name: Prepare repository (on workflow_dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git fetch origin master:refs/remotes/origin/master --tags --force
          git remote set-head origin -a
          git checkout ${{ github.ref_name }}
          git pull --force

      - name: Generate docs
        run: |
          cd docs
          poxy --verbose --git-tags --min-version v2.0.0 --no-squash-patches

      - name: Deploy (master)
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref_name == 'master' || github.event_name == 'release' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: Update documentation (GitHub actions deploy)

      - name: Deploy (branch)
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref_name != 'master' && github.event_name != 'release' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          destination_dir: ref/${{ github.ref_name }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: Update documentation (GitHub actions deploy)
