name: Documentation

on:
  push:
    branches:
      - master
      - v*/dev
    paths:
      - "**.h"
      - "**.hpp"
      - "**.dox"
      - "**.md"
      - "docs/**"
      - "**/docs.yml"
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install --no-install-recommends git python3 python3-pip doxygen
          sudo -H pip3 install --upgrade poxy

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate docs
        run: |
          cd docs
          poxy --verbose

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          destination_dir: ${{ github.ref_name }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: Update documentation (GitHub actions deploy)
